// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class MainUI {
public:
  MainUI();
  Fl_Double_Window *uiwindow;
  Fl_Button *animateBtn;
private:
  inline void cb_animateBtn_i(Fl_Button*, void*);
  static void cb_animateBtn(Fl_Button*, void*);
public:
  Fl_Button *btnHWTexMap;
private:
  inline void cb_btnHWTexMap_i(Fl_Button*, void*);
  static void cb_btnHWTexMap(Fl_Button*, void*);
public:
  Fl_Button *btnHWFilled;
private:
  inline void cb_btnHWFilled_i(Fl_Button*, void*);
  static void cb_btnHWFilled(Fl_Button*, void*);
public:
  Fl_Button *btnHWWireFrame;
private:
  inline void cb_btnHWWireFrame_i(Fl_Button*, void*);
  static void cb_btnHWWireFrame(Fl_Button*, void*);
public:
  Fl_Button *btnGPUShader;
private:
  inline void cb_btnGPUShader_i(Fl_Button*, void*);
  static void cb_btnGPUShader(Fl_Button*, void*);
  unsigned int width; 
  unsigned int height; 
public:
  void show();
  void animation();
  void showHWTexMap();
  void showHWFilledMode();
  void showHWWireFrameMode();
  void showGPUShader();
};
#endif
