// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_File_Input.H>

class MainUI {
public:
  MainUI();
  Fl_Double_Window *uiwindow;
private:
  inline void cb_Resize_i(Fl_Button*, void*);
  static void cb_Resize(Fl_Button*, void*);
public:
  Fl_Spinner *widthSpinner;
  Fl_Spinner *heightSpinner;
private:
  inline void cb_Set_i(Fl_Button*, void*);
  static void cb_Set(Fl_Button*, void*);
public:
  Fl_Spinner *redSpinner;
  Fl_Spinner *greenSpinner;
  Fl_Spinner *blueSpinner;
  Fl_Spinner *alphaSpinner;
private:
  inline void cb_Set1_i(Fl_Button*, void*);
  static void cb_Set1(Fl_Button*, void*);
public:
  Fl_Spinner *xSpinner;
  Fl_Spinner *ySpinner;
  Fl_Button *resetBtn;
private:
  inline void cb_resetBtn_i(Fl_Button*, void*);
  static void cb_resetBtn(Fl_Button*, void*);
public:
  Fl_Button *SetRectangle;
private:
  inline void cb_SetRectangle_i(Fl_Button*, void*);
  static void cb_SetRectangle(Fl_Button*, void*);
public:
  Fl_Spinner *x0Spinner;
  Fl_Spinner *y0Spinner;
  Fl_Spinner *x1Spinner;
  Fl_Spinner *y1Spinner;
  Fl_Button *setCircle;
private:
  inline void cb_setCircle_i(Fl_Button*, void*);
  static void cb_setCircle(Fl_Button*, void*);
public:
  Fl_Spinner *xcSpinner;
  Fl_Spinner *ycSpinner;
  Fl_Spinner *radiusSpinner;
  Fl_Button *saveBtn;
private:
  inline void cb_saveBtn_i(Fl_Button*, void*);
  static void cb_saveBtn(Fl_Button*, void*);
public:
  Fl_File_Input *saveInput;
  Fl_Button *readBtn;
private:
  inline void cb_readBtn_i(Fl_Button*, void*);
  static void cb_readBtn(Fl_Button*, void*);
public:
  Fl_File_Input *readInput;
  Fl_Button *animateBtn;
private:
  inline void cb_animateBtn_i(Fl_Button*, void*);
  static void cb_animateBtn(Fl_Button*, void*);
  inline void cb_Draw_i(Fl_Button*, void*);
  static void cb_Draw(Fl_Button*, void*);
public:
  Fl_Spinner *x00Spinner;
  Fl_Spinner *y00Spinner;
  Fl_Spinner *x11Spinner;
  Fl_Spinner *y11Spinner;
  Fl_Spinner *x22Spinner;
  Fl_Spinner *y22Spinner;
  void show();
  void resize();
  void setbgr();
  void setonept();
  void reset();
  void setRectangle();
  void drawCircle();
  void saveImage();
  void readImage();
  void animation();
  void drawTriangle();
};
#endif
